### ISSUE TITLE
Handle invalid YAML more gracefully

### ISSUE THREAD

**Issue by mcbridem** [usnews/smoketest#29]
If you try to run Smoketest with invalid YAML, it throws an exception. Perhaps this could be handled more gracefully.

Instead of this:
```
$ ./venv/bin/smoketest -vv expectations/e.yaml 
Traceback (most recent call last):
  File "./venv/bin/smoketest", line 11, in <module>
    load_entry_point('Smoketest==1.0.0', 'console_scripts', 'smoketest')()
  File "/Users/mmcbride/Documents/git/smoketest/venv/lib/python2.7/site-packages/smoketest/__init__.py", line 132, in main
    directives.extend(generate_directives_from_file(filename, args))
  File "/Users/mmcbride/Documents/git/smoketest/venv/lib/python2.7/site-packages/smoketest/directives.py", line 274, in _generate_directives_from_json_or_yaml
    input_ = yaml.load(file_)
  File "/Users/mmcbride/Documents/git/smoketest/venv/lib/python2.7/site-packages/yaml/__init__.py", line 71, in load
    return loader.get_single_data()
  File "/Users/mmcbride/Documents/git/smoketest/venv/lib/python2.7/site-packages/yaml/constructor.py", line 37, in get_single_data
    node = self.get_single_node()
  File "/Users/mmcbride/Documents/git/smoketest/venv/lib/python2.7/site-packages/yaml/composer.py", line 36, in get_single_node
    document = self.compose_document()
  File "/Users/mmcbride/Documents/git/smoketest/venv/lib/python2.7/site-packages/yaml/composer.py", line 55, in compose_document
    node = self.compose_node(None, None)
  File "/Users/mmcbride/Documents/git/smoketest/venv/lib/python2.7/site-packages/yaml/composer.py", line 82, in compose_node
    node = self.compose_sequence_node(anchor)
  File "/Users/mmcbride/Documents/git/smoketest/venv/lib/python2.7/site-packages/yaml/composer.py", line 111, in compose_sequence_node
    node.value.append(self.compose_node(node, index))
  File "/Users/mmcbride/Documents/git/smoketest/venv/lib/python2.7/site-packages/yaml/composer.py", line 84, in compose_node
    node = self.compose_mapping_node(anchor)
  File "/Users/mmcbride/Documents/git/smoketest/venv/lib/python2.7/site-packages/yaml/composer.py", line 127, in compose_mapping_node
    while not self.check_event(MappingEndEvent):
  File "/Users/mmcbride/Documents/git/smoketest/venv/lib/python2.7/site-packages/yaml/parser.py", line 98, in check_event
    self.current_event = self.state()
  File "/Users/mmcbride/Documents/git/smoketest/venv/lib/python2.7/site-packages/yaml/parser.py", line 439, in parse_block_mapping_key
    "expected <block end>, but found %r" % token.id, token.start_mark)
yaml.parser.ParserError: while parsing a block mapping
  in "expectations/e.yaml", line 11, column 5
expected <block end>, but found '-'
  in "expectations/e.yaml", line 14, column 5
```

Maybe it could be like this:
```
$ ./venv/bin/smoketest -vv expectations/e.yaml 
Yo, there's a problem with "expectations/e.yaml".
```

**Comment by bpeebles** [comment]
Have some of the error could still be useful. We could not print the full traceback in this case but just print the message along with some other text to make it friendlier if we don't want to do more complex figuring out what's wrong with the YAML.

**Comment by mcbridem** [comment]
Agreed. Even something like this would be nicer and friendlier:

```
$ ./venv/bin/smoketest -vv expectations/e.yaml
yaml.parser.ParserError: while parsing a block mapping
  in "expectations/e.yaml", line 11, column 5
expected <block end>, but found '-'
  in "expectations/e.yaml", line 14, column 5
```

That at least avoids the 26 lines of file paths, line numbers, and code excerpts.

Somewhat related, the behavior when an invalid file name is given is similarly pretty aggressive and verbose. Perhaps better suited to a separate issue, tho.

**Comment by mcbridem** [comment]
For YAML files, there seems to be three distinct cases: missing input files, files with structurally invalid YAML, and files with invalid Smoketest YAML (such as `ur:` instead of `url:`). I'm not sure we can easily catch the third case, but catching the first two cases is potentially straightforward:

```diff
$ git diff -w | cat
diff --git a/smoketest/directives.py b/smoketest/directives.py
index fe057f7..3eb7694 100644
--- a/smoketest/directives.py
+++ b/smoketest/directives.py
@@ -267,11 +267,21 @@ class FileParser(object):
 
     def _generate_directives_from_json_or_yaml(self):
         # Load input
+        try:
             with open(self.filename, 'r') as file_:
                 if self.filename.endswith('json'):
                     input_ = json.load(file_)
                 else:
+                    try:
                         input_ = yaml.safe_load(file_)
+                    except (yaml.scanner.ScannerError, ):
+                        print(u'There was a problem parsing "{0}".'.format(
+                            self.filename
+                        ))
+                        sys.exit(1)
+        except (IOError, ):
+            print(u'There was a problem opening "{0}".'.format(self.filename))
+            sys.exit(1)
 
         # Parse input
         directives = []
```

**Comment by mcbridem** [comment]
Christopher notes we'll likely want to catch `yaml.parser.ParserError` as well. Perhaps we want `YAMLError`?
