### ISSUE TITLE
Support non-ASCII boolean attributes in YAML expectation files

### ISSUE THREAD

**Issue by mcbridem** [usnews/smoketest#38]
For a URL such as <https://www.citylab.com/amp/article/551309/>, it has this HTML:

```html
<html ⚡ lang="en" itemscope itemtype="https://schema.org/NewsArticle"> 
```

Testing this non-ASCII boolean attribute (`⚡`) seems to be impossible. Here's what I'm trying:

```yaml
-   directive: check
    url: https://www.citylab.com/amp/article/551309/
    html:
    -   selector: html
        attribute: '⚡'
        contains: ''
```

Here's the result:

```
mmcbride@local:~/Documents/git/smoketests$ ./venv/bin/smoketest -vvv expectations/boolean-attributes.yaml 

url: https://www.citylab.com/amp/article/551309/?_=1537562048980
test: status code is 200
result: status code was 200
passed: True
time: 0:00:00.504759
platform: desktop
hops: 0
Exception in thread Thread-16:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/mmcbride/Documents/git/smoketests/venv/lib/python2.7/site-packages/smoketest/threads.py", line 26, in runner
    directive.run()
  File "/Users/mmcbride/Documents/git/smoketests/venv/lib/python2.7/site-packages/smoketest/directives.py", line 173, in run
    failed_urls_ |= self._run_for_platform(platform)
  File "/Users/mmcbride/Documents/git/smoketests/venv/lib/python2.7/site-packages/smoketest/directives.py", line 197, in _run_for_platform
    self.logger.log_test_result(url, test, result, response, platform, self.follow_redirects)
  File "/Users/mmcbride/Documents/git/smoketests/venv/lib/python2.7/site-packages/smoketest/loggers.py", line 139, in log_test_result
    follow_redirects,
  File "/Users/mmcbride/Documents/git/smoketests/venv/lib/python2.7/site-packages/smoketest/loggers.py", line 252, in log_failure
    test_desc = test.description
  File "/Users/mmcbride/Documents/git/smoketests/venv/lib/python2.7/site-packages/smoketest/tests.py", line 738, in description
    self.text_matching_method.description,
UnicodeEncodeError: 'ascii' codec can't encode character u'\u26a1' in position 0: ordinal not in range(128)


Elapsed time: 1.77798008919
Number of successes: 1
Number of failures: 0
Number of errors: 0
```

**Comment by malerichc** [comment]
I think this was resolved completely by https://github.com/usnews/smoketest/pull/47, please reopen it if not though!
