### ISSUE TITLE
Smoketest throws an exception for non-matching HTTP response tests

### ISSUE THREAD

**Issue by mcbridem** [usnews/smoketest#41]
Smoketest throws an exception for non-matching HTTP response tests. Example expectations file:

```yaml
-   directive: check
    url: https://www.theatlantic.com/
    headers:
    -
        header: Some-Fake-Header
        contains: 'Hello'
```

This results in an exception being thrown when using the default shell output format:

```
$ ./venv/bin/smoketest -vv expectations/s.yaml 
.Exception in thread Thread-16:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/mmcbride/Documents/git/smoketests/venv/lib/python2.7/site-packages/smoketest/threads.py", line 26, in runner
    directive.run()
  File "/Users/mmcbride/Documents/git/smoketests/venv/lib/python2.7/site-packages/smoketest/directives.py", line 170, in run
    failed_urls_ |= self._run_for_platform(platform)
  File "/Users/mmcbride/Documents/git/smoketests/venv/lib/python2.7/site-packages/smoketest/directives.py", line 194, in _run_for_platform
    self.logger.log_test_result(url, test, result, response, platform, self.follow_redirects)
  File "/Users/mmcbride/Documents/git/smoketests/venv/lib/python2.7/site-packages/smoketest/loggers.py", line 123, in log_test_result
    if result:
  File "/Users/mmcbride/Documents/git/smoketests/venv/lib/python2.7/site-packages/smoketest/tests.py", line 644, in __nonzero__
    match = self.test.text_matching_method(actual_value)
  File "/Users/mmcbride/Documents/git/smoketests/venv/lib/python2.7/site-packages/smoketest/tests.py", line 310, in __call__
    match = self.text_to_match in text_to_test
TypeError: argument of type 'NoneType' is not iterable


Elapsed time: 4.36708593369
Number of successes: 1
Number of failures: 0
Number of errors: 0
```

More perniciously, this exception gets somewhat swallowed when the JSON output format is used:

```
$ ./venv/bin/smoketest -fjson -vv expectations/s.yaml 
Exception in thread Thread-16:
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/Users/mmcbride/Documents/git/smoketests/venv/lib/python2.7/site-packages/smoketest/threads.py", line 26, in runner
    directive.run()
  File "/Users/mmcbride/Documents/git/smoketests/venv/lib/python2.7/site-packages/smoketest/directives.py", line 170, in run
    failed_urls_ |= self._run_for_platform(platform)
  File "/Users/mmcbride/Documents/git/smoketests/venv/lib/python2.7/site-packages/smoketest/directives.py", line 194, in _run_for_platform
    self.logger.log_test_result(url, test, result, response, platform, self.follow_redirects)
  File "/Users/mmcbride/Documents/git/smoketests/venv/lib/python2.7/site-packages/smoketest/loggers.py", line 123, in log_test_result
    if result:
  File "/Users/mmcbride/Documents/git/smoketests/venv/lib/python2.7/site-packages/smoketest/tests.py", line 644, in __nonzero__
    match = self.test.text_matching_method(actual_value)
  File "/Users/mmcbride/Documents/git/smoketests/venv/lib/python2.7/site-packages/smoketest/tests.py", line 310, in __call__
    match = self.text_to_match in text_to_test
TypeError: argument of type 'NoneType' is not iterable

{
    "configuration": {
        "cachebust": true,
        "dry_run": false,
        "level": "live",
        "delay_between_passes": 0,
        "verbosity": 2,
        "format": "json",
        "quiet": false,
        "passes": 1,
        "threads": 16,
        "user_agent": "Smoketest (https://www.usnews.com)",
        "input_filenames": [
            "expectations/s.yaml"
        ],
        "output": "",
        "scheme": null,
        "port": null
    },
    "results": [
        {
            "summary": {
                "Number of successes": "1",
                "Number of failures": "0",
                "Number of errors": "0",
                "Elapsed time": "4.74506807327"
            },
            "urls": []
        }
    ]
}
```

In particular, Smoketest reports 1 success, 0 failures, and 0 errors in the JSON output, but this is wrong!

**Comment by bengmur** [comment]
I opened #42 to address this particular issue, but would it make sense to also expand `HeaderTest` to support testing for header presence, rather than only testing the value?

**Comment by mcbridem** [comment]
Thanks for the pull request.

I do not have a use-case for testing exclusively for the presence of an HTTP response header and I can't currently think of one. If someone had an immediate need to do so, `contains: ''` would work.
